[package]
name = "devjournal"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.25"
tui-textarea = "0.2.0"
serde = { version = "1.0.152", features = ["serde_derive"] }
bincode = "1.3.3"
platform-dirs = "0.3.0"
aes-gcm = "0.10.1"
rand = "0.8.5"
